export const UI_CONSTANTS = {
  HEADER_HEIGHT: 60,
  BOTTOM_TAB_HEIGHT: 55,
  DEFAULT_PADDING: 15,
  BORDER_RADIUS: 10,
  ANIMATION_DURATION: 300,
} as const;

export const TIME_CONSTANTS = {
  MESSAGE_DEBOUNCE: 300, // ms
  SEARCH_DEBOUNCE: 500, // ms
  LOCATION_THROTTLE: 1000, // ms
  CHAT_REFRESH: 10000, // ms
  NOTIFICATION_CHECK: 60000, // ms
} as const;