name: dog_match_app
description: A Flutter app for dog matchmaking with profiles, chat, location-based discovery, and notifications.
publish_to: 'none' # remove if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Backend
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^15.1.0+1

  # Images & Media
  image_picker: ^1.0.4

  # Location & Maps
  geolocator: ^14.0.2
  geoflutterfire_plus: ^0.0.33
  google_maps_flutter: ^2.13.1
  google_maps_cluster_manager: ^3.1.0

  # Networking
  http: ^1.1.2

  # Formatting & Utils
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ # if you plan to add custom icons, images