// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXfxP0WvGP75SWTQ6D4lEtv9vGDcNVJ34',
    appId: '1:436329415809:web:369d562f43c0eb54737980',
    messagingSenderId: '436329415809',
    projectId: 'dog-match-app-fb26e',
    authDomain: 'dog-match-app-fb26e.firebaseapp.com',
    storageBucket: 'dog-match-app-fb26e.firebasestorage.app',
    measurementId: 'G-F3XK3D06XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNFyVm6XotYMrTjQPsgmwiIPsAvDfVMc',
    appId: '1:436329415809:android:c3e773e153f2b0a1737980',
    messagingSenderId: '436329415809',
    projectId: 'dog-match-app-fb26e',
    storageBucket: 'dog-match-app-fb26e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWeu_bUK9J3qE4VlEz8_I1b8TZJay85Ko',
    appId: '1:436329415809:ios:e1306803bbc701bc737980',
    messagingSenderId: '436329415809',
    projectId: 'dog-match-app-fb26e',
    storageBucket: 'dog-match-app-fb26e.firebasestorage.app',
    iosBundleId: 'com.example.dogMatchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXfxP0WvGP75SWTQ6D4lEtv9vGDcNVJ34',
    appId: '1:436329415809:web:c3f41ee3eb8c10b7737980',
    messagingSenderId: '436329415809',
    projectId: 'dog-match-app-fb26e',
    authDomain: 'dog-match-app-fb26e.firebaseapp.com',
    storageBucket: 'dog-match-app-fb26e.firebasestorage.app',
    measurementId: 'G-LW5JNP3TFY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWeu_bUK9J3qE4VlEz8_I1b8TZJay85Ko',
    appId: '1:436329415809:ios:e1306803bbc701bc737980',
    messagingSenderId: '436329415809',
    projectId: 'dog-match-app-fb26e',
    storageBucket: 'dog-match-app-fb26e.firebasestorage.app',
    iosBundleId: 'com.example.dogMatchApp',
  );

}